language: c

before_install:
  - wget http://sourceforge.net/projects/devkitpro/files/Automated%20Installer/devkitARMupdate.pl
  - export DEVKITPRO=/home/travis/devkitPro
  - export DEVKITARM=${DEVKITPRO}/devkitARM

install:
  - sudo perl devkitARMupdate.pl

script:
  - make
  - mv output/Launcher.dat .

env:
  global:
    secure: "QeQ3FDs8vOcB7+TJBPIszTPo6EuYOTcqTlC15fAXTHLLnGsY36ySSMKXKq9aV5mqJr9t92WGY169fAW35vg9wwQAx09A2EIEkaqLysozkNxaR9LralgwEEAXXJP2lD5NvJ0n13PMPloGyDCnjBRUjJ+WdDz5H6F329PbItKo5uE="

after_success:
  - >
    if [ "$TRAVIS_BRANCH" == "master" ]; then
        GITDATE="`git show -s --date=short --format='%ad' | sed 's/-//g'`"
        GITREV="`git show -s --format='%h'`"
        REV_NAME="decrypt9-${GITDATE}-${GITREV}-browser"

        sudo apt-get -qq install lftp p7zip-full
        mkdir "$REV_NAME"

        cp -R README.md Launcher.dat scripts "$REV_NAME"
        7z a "$REV_NAME" "$REV_NAME/*"
        ARCHIVE_NAME="${REV_NAME}.7z"
        lftp -c "open -u builds,$BUILD_PASSWORD sftp://archshift.com; put -O '/decrypt9/nightly/browser' '$ARCHIVE_NAME'"
    fi
